### ISSUE TITLE
skktool の openlab への反映

### ISSUE THREAD

**Issue by yutopia** [skk-dev/skktools#10]
#9 より。

現在 skktools は github 上でメンテされていて SKKJISYO の配布元である openlab にレポジトリが置いてないが、辞書のメンテに skktools が使用されているようである。
(どのタイミングで更新されているかは不明)
github の開発内容を openlab に反映する必要があるかも？

cron か何かが走っているとしたら、延々とエラーログをどこかに吐いてるかもしれません。
結構 openlab で色々な cron が走ってるっぽいので。

**Comment by ohaguro123** [comment]
SKK辞書の更新はgithubのみであることが宣言されているので、「github の開発内容を openlab に反映する必要」は無いように思えます。
