### ISSUE TITLE
asayaKe.rb などの Ruby の新バージョン対応

### ISSUE THREAD

**Issue by toshjp** [skk-dev/skktools#12]
私は以前から標準辞書を asayaKe.rb で処理していましたが、Ubuntu 18.04 ベースのシステムで Ruby 2.5.1 の環境に移行したところ、asayaKe.rb が次のようなエラーで使用できませんでした。

`/usr/bin/env: ‘ruby -E euc-jis-2004:utf-8’: No such file or directory`

すでに一部で Ruby の新バージョンへの対応が進められていたようですが、まだ未対応のツールもあるようです。aozora2skk.rb などと同様、冒頭の env の引数の処理を変更することで動作したので当面困りませんが、今後の対応をお願いできればと思います。

**Comment by kyohsuke** [comment]
@toshjp 動作確認ありがとうございます！
