### ISSUE TITLE
skktools 1.3.4 として現在の master を出したいです

### ISSUE THREAD

**Issue by kyohsuke** [skk-dev/skktools#14]
`skkdic-*` は変更されていないのですが、先日の filters 配下を修正した件があるので可能であれば skktools のバージョンを1つ上げて 1.3.4 として出したいです。

@tkita さん、お手空きの際で構いませんので、検討して頂けませんでしょうか。

宜しくお願い致します。

**Comment by tkita** [comment]
release することはまったく構わないのですが、ひとつだけ作業をお願いします。
filters/README.md に「バージョン 2.1 以降の ruby が必要です」と記載があります。
私、普段まったく Ruby を使っていないため、最近の Ruby の仕様を知りません。
skktools-1.3.3 が動作するRubyのバージョンと、#13 によって切り捨てられた Ruby のバージョンなどがあるのかなと思っています。
この辺を filters/README.md に記載していただけるでしょうか。

**Comment by kyohsuke** [comment]
了解です、確認します

**Comment by kyohsuke** [comment]
はい、同一の Ruby バージョンで大丈夫です。

**Comment by tkita** [comment]
先ほど（8/8, 22:00頃）リリースタグ skktools-1_3_4 を打ちました。
