### ISSUE TITLE
ruby バージョンについて

### ISSUE THREAD

**Issue by yutopia** [skk-dev/skktools#6]
公式で、ruby 2.0.0 の保守は2016 年 2 月 24 日で終了することになっています。
skktoolsで使用されている ruby script がこれに対応する必要があるかどうか調査の必要あり？

**Comment by kyohsuke** [comment]
to @yutopia 

気付くのが遅れて申し訳ありません。

> 公式で、ruby 2.0.0 の保守は2016 年 2 月 24 日で終了することになっています。
skktoolsで使用されている ruby script がこれに対応する必要があるかどうか調査の必要あり？

重要なのはツールを必要とする人がサポート対象の環境が使えるのかどうかだと思います。

C言語で記述されている方は clang 対応しつつも古いGCCでビルドできる記述にしているので、
ツール群も Ruby 1.8 や 1.9 で動く記述のままにした方が良いんじゃないかな、と考えています。

とはいえサポート外だとセキュリティ修正されない問題もありますので、
対応の必要があればこの Issue を私にアサインして頂ければ確認して Ruby 2.1.x に対応します。

**Comment by yutopia** [comment]
@kyohsuke 
> 重要なのはツールを必要とする人がサポート対象の環境が使えるのかどうかだと思います。
おっしゃる通りだと思います。
Ruby 2.0.0 のサポートが切れたとは言っても、2.0.0 以前のバージョンで作業されてる方も当然いると思いますし。ddskk の後方互換性の問題と同じではあるのですが。

skktools のトラフィックはあまり無いようなのですが、SKK 辞書が他の環境でも使われていることを考えると、気付いたときに対応しておくのがベターかと。

可能な限りでお願いいたします。
ちなみに、2.0.0からの移行先に2.1.xは推奨されてないので、できれば 2.2.x で。。
https://www.ruby-lang.org/ja/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

**Comment by kyohsuke** [comment]
@yutopia 

> 可能な限りでお願いいたします。
ちなみに、2.0.0からの移行先に2.1.xは推奨されてないので、できれば 2.2.x で。。
https://www.ruby-lang.org/ja/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

了解です、*.rb の物を 2.2.x 化していきます。
完了したら pull request の形で投稿します。
